[build]
  # Directory to change to before starting a build
  base = "."
  # Build command with explicit install and debugging
  command = "npm ci && npm run build"
  # Publish directory for Next.js
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Disable secrets scanning for template repository
  # These are configuration values, not actual secrets
  SECRETS_SCAN_ENABLED = "false"
  # Ensure npm install runs in production mode
  NPM_FLAGS = "--production=false"

# Function configuration for Next.js on Netlify
[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for dynamic API routes
[[redirects]]
  from = "/api/chats/:id/messages"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/chats/:id/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/chats"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/projects/:id/chats/:chatId/messages"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/api/projects/:id/chats"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Environment variables must be set in Netlify dashboard
# Do not hardcode secrets in this file for security reasons
# 
# Required environment variables:
# - HUB_URL: URL of your EMtek Hub instance
# - NEXT_PUBLIC_HUB_URL: URL of your EMtek Hub instance (client-side)
# - NEXT_PUBLIC_TOOL_URL: Your deployed site URL
# - TOOL_SLUG: Unique identifier for your tool
# - NEXT_PUBLIC_TOOL_NAME: Display name for your tool
# - NEXT_PUBLIC_TOOL_DESCRIPTION: Brief description of your tool

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' *"
