[build]
  # Directory to change to before starting a build
  base = "."
  # Default build command for Next.js
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  EMTEK_HUB_URL = "https://emtekhub.netlify.app"
  TOOL_SLUG = "test-tool-template"
  NEXTAUTH_SECRET = "your-production-nextauth-secret-change-this"
  NEXT_PUBLIC_TOOL_NAME = "Test Tool Template"
  NEXT_PUBLIC_TOOL_DESCRIPTION = "Testing the EMtek Hub SSO integration"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://emtekhub.netlify.app"
