[build]
  # Directory to change to before starting a build
  base = "."
  # Default build command for Next.js
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  # Disable secrets scanning for template repository
  # These are configuration values, not actual secrets
  SECRETS_SCAN_ENABLED = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables must be set in Netlify dashboard
# Do not hardcode secrets in this file for security reasons
# 
# Required environment variables:
# - EMTEK_HUB_URL: URL of your EMtek Hub instance
# - TOOL_SLUG: Unique identifier for your tool
# - NEXTAUTH_URL: Your deployed site URL  
# - NEXTAUTH_SECRET: Random secret for session encryption
# - NEXT_PUBLIC_TOOL_NAME: Display name for your tool
# - NEXT_PUBLIC_TOOL_DESCRIPTION: Brief description of your tool

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' *"
